using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureType
{

    private SignedInfoType signedInfoField;

    private SignatureValueType signatureValueField;

    private KeyInfoType keyInfoField;

    private string idField;

    /// <remarks/>
    public SignedInfoType SignedInfo
    {
        get
        {
            return this.signedInfoField;
        }
        set
        {
            this.signedInfoField = value;
        }
    }

    /// <remarks/>
    public SignatureValueType SignatureValue
    {
        get
        {
            return this.signatureValueField;
        }
        set
        {
            this.signatureValueField = value;
        }
    }

    /// <remarks/>
    public KeyInfoType KeyInfo
    {
        get
        {
            return this.keyInfoField;
        }
        set
        {
            this.keyInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoType
{

    private SignedInfoTypeCanonicalizationMethod canonicalizationMethodField;

    private SignedInfoTypeSignatureMethod signatureMethodField;

    private ReferenceType referenceField;

    private string idField;

    /// <remarks/>
    public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod
    {
        get
        {
            return this.canonicalizationMethodField;
        }
        set
        {
            this.canonicalizationMethodField = value;
        }
    }

    /// <remarks/>
    public SignedInfoTypeSignatureMethod SignatureMethod
    {
        get
        {
            return this.signatureMethodField;
        }
        set
        {
            this.signatureMethodField = value;
        }
    }

    /// <remarks/>
    public ReferenceType Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoTypeCanonicalizationMethod
{

    private string algorithmField;

    public SignedInfoTypeCanonicalizationMethod()
    {
        this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class X509DataType
{

    private byte[] x509CertificateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] X509Certificate
    {
        get
        {
            return this.x509CertificateField;
        }
        set
        {
            this.x509CertificateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyInfoType
{

    private X509DataType x509DataField;

    private string idField;

    /// <remarks/>
    public X509DataType X509Data
    {
        get
        {
            return this.x509DataField;
        }
        set
        {
            this.x509DataField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureValueType
{

    private string idField;

    private byte[] valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class TransformType
{

    private string[] xPathField;

    private TTransformURI algorithmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XPath")]
    public string[] XPath
    {
        get
        {
            return this.xPathField;
        }
        set
        {
            this.xPathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TTransformURI Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public enum TTransformURI
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
    httpwwww3org200009xmldsigenvelopedsignature,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
    httpwwww3orgTR2001RECxmlc14n20010315,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceType
{

    private TransformType[] transformsField;

    private ReferenceTypeDigestMethod digestMethodField;

    private byte[] digestValueField;

    private string idField;

    private string uRIField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
    public TransformType[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }

    /// <remarks/>
    public ReferenceTypeDigestMethod DigestMethod
    {
        get
        {
            return this.digestMethodField;
        }
        set
        {
            this.digestMethodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] DigestValue
    {
        get
        {
            return this.digestValueField;
        }
        set
        {
            this.digestValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceTypeDigestMethod
{

    private string algorithmField;

    public ReferenceTypeDigestMethod()
    {
        this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoTypeSignatureMethod
{

    private string algorithmField;

    public SignedInfoTypeSignatureMethod()
    {
        this.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ReducaoZ
{

    private ReducaoZMensagem mensagemField;

    private SignatureType signatureField;

    private string versaoField;

    /// <remarks/>
    public ReducaoZMensagem Mensagem
    {
        get
        {
            return this.mensagemField;
        }
        set
        {
            this.mensagemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Versao
    {
        get
        {
            return this.versaoField;
        }
        set
        {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagem
{

    private ReducaoZMensagemEstabelecimento estabelecimentoField;

    private ReducaoZMensagemPafEcf pafEcfField;

    private ReducaoZMensagemEcf ecfField;

    private string[] textField;

    /// <remarks/>
    public ReducaoZMensagemEstabelecimento Estabelecimento
    {
        get
        {
            return this.estabelecimentoField;
        }
        set
        {
            this.estabelecimentoField = value;
        }
    }

    /// <remarks/>
    public ReducaoZMensagemPafEcf PafEcf
    {
        get
        {
            return this.pafEcfField;
        }
        set
        {
            this.pafEcfField = value;
        }
    }

    /// <remarks/>
    public ReducaoZMensagemEcf Ecf
    {
        get
        {
            return this.ecfField;
        }
        set
        {
            this.ecfField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEstabelecimento
{

    private string ieField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string Ie
    {
        get
        {
            return this.ieField;
        }
        set
        {
            this.ieField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemPafEcf
{

    private string numeroCredenciamentoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string NumeroCredenciamento
    {
        get
        {
            return this.numeroCredenciamentoField;
        }
        set
        {
            this.numeroCredenciamentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcf
{

    private string numeroFabricacaoField;

    private ReducaoZMensagemEcfDadosReducaoZ dadosReducaoZField;

    /// <remarks/>
    public string NumeroFabricacao
    {
        get
        {
            return this.numeroFabricacaoField;
        }
        set
        {
            this.numeroFabricacaoField = value;
        }
    }

    /// <remarks/>
    public ReducaoZMensagemEcfDadosReducaoZ DadosReducaoZ
    {
        get
        {
            return this.dadosReducaoZField;
        }
        set
        {
            this.dadosReducaoZField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcfDadosReducaoZ
{

    private System.DateTime dataReferenciaField;

    private System.DateTime dataHoraEmissaoField;

    private string cRZField;

    private string cOOField;

    private string cROField;

    private string vendaBrutaDiariaField;

    private string gtField;

    private ReducaoZMensagemEcfDadosReducaoZTotalizadorParcial[] totalizadoresParciaisField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime DataReferencia
    {
        get
        {
            return this.dataReferenciaField;
        }
        set
        {
            this.dataReferenciaField = value;
        }
    }

    /// <remarks/>
    public System.DateTime DataHoraEmissao
    {
        get
        {
            return this.dataHoraEmissaoField;
        }
        set
        {
            this.dataHoraEmissaoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string CRZ
    {
        get
        {
            return this.cRZField;
        }
        set
        {
            this.cRZField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string COO
    {
        get
        {
            return this.cOOField;
        }
        set
        {
            this.cOOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string CRO
    {
        get
        {
            return this.cROField;
        }
        set
        {
            this.cROField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string VendaBrutaDiaria
    {
        get
        {
            return this.vendaBrutaDiariaField;
        }
        set
        {
            this.vendaBrutaDiariaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string GT
    {
        get
        {
            return this.gtField;
        }
        set
        {
            this.gtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TotalizadorParcial", IsNullable = false)]
    public ReducaoZMensagemEcfDadosReducaoZTotalizadorParcial[] TotalizadoresParciais
    {
        get
        {
            return this.totalizadoresParciaisField;
        }
        set
        {
            this.totalizadoresParciaisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcfDadosReducaoZTotalizadorParcial
{

    private string nomeField;

    private string valorField;

    private ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicos produtosServicosField;

    /// <remarks/>
    public string Nome
    {
        get
        {
            return this.nomeField;
        }
        set
        {
            this.nomeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string Valor
    {
        get
        {
            return this.valorField;
        }
        set
        {
            this.valorField = value;
        }
    }

    /// <remarks/>
    public ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicos ProdutosServicos
    {
        get
        {
            return this.produtosServicosField;
        }
        set
        {
            this.produtosServicosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicos
{

    private ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosProduto[] produtoField;

    private ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosServico[] servicoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Produto")]
    public ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosProduto[] Produto
    {
        get
        {
            return this.produtoField;
        }
        set
        {
            this.produtoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Servico")]
    public ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosServico[] Servico
    {
        get
        {
            return this.servicoField;
        }
        set
        {
            this.servicoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosProduto
{

    private string descricaoField;

    private string codigoGTINField;

    private string codigoCESTField;

    private string codigoNCMSHField;

    private string codigoProprioField;

    private string quantidadeField;

    private string unidadeField;

    private string valorDescontoField;

    private string valorAcrescimoField;

    private string valorCancelamentoField;

    private string valorTotalLiquidoField;

    /// <remarks/>
    public string Descricao
    {
        get
        {
            return this.descricaoField;
        }
        set
        {
            this.descricaoField = value;
        }
    }

    /// <remarks/>
    public string CodigoGTIN
    {
        get
        {
            return this.codigoGTINField;
        }
        set
        {
            this.codigoGTINField = value;
        }
    }

    /// <remarks/>
    public string CodigoCEST
    {
        get
        {
            return this.codigoCESTField;
        }
        set
        {
            this.codigoCESTField = value;
        }
    }

    /// <remarks/>
    public string CodigoNCMSH
    {
        get
        {
            return this.codigoNCMSHField;
        }
        set
        {
            this.codigoNCMSHField = value;
        }
    }

    /// <remarks/>
    public string CodigoProprio
    {
        get
        {
            return this.codigoProprioField;
        }
        set
        {
            this.codigoProprioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string Quantidade
    {
        get
        {
            return this.quantidadeField;
        }
        set
        {
            this.quantidadeField = value;
        }
    }

    /// <remarks/>
    public string Unidade
    {
        get
        {
            return this.unidadeField;
        }
        set
        {
            this.unidadeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorDesconto
    {
        get
        {
            return this.valorDescontoField;
        }
        set
        {
            this.valorDescontoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorAcrescimo
    {
        get
        {
            return this.valorAcrescimoField;
        }
        set
        {
            this.valorAcrescimoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorCancelamento
    {
        get
        {
            return this.valorCancelamentoField;
        }
        set
        {
            this.valorCancelamentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorTotalLiquido
    {
        get
        {
            return this.valorTotalLiquidoField;
        }
        set
        {
            this.valorTotalLiquidoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReducaoZMensagemEcfDadosReducaoZTotalizadorParcialProdutosServicosServico
{

    private string descricaoField;

    private string codigoProprioField;

    private string quantidadeField;

    private string unidadeField;

    private string valorDescontoField;

    private string valorAcrescimoField;

    private string valorCancelamentoField;

    private string valorTotalLiquidoField;

    /// <remarks/>
    public string Descricao
    {
        get
        {
            return this.descricaoField;
        }
        set
        {
            this.descricaoField = value;
        }
    }

    /// <remarks/>
    public string CodigoProprio
    {
        get
        {
            return this.codigoProprioField;
        }
        set
        {
            this.codigoProprioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string Quantidade
    {
        get
        {
            return this.quantidadeField;
        }
        set
        {
            this.quantidadeField = value;
        }
    }

    /// <remarks/>
    public string Unidade
    {
        get
        {
            return this.unidadeField;
        }
        set
        {
            this.unidadeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorDesconto
    {
        get
        {
            return this.valorDescontoField;
        }
        set
        {
            this.valorDescontoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorAcrescimo
    {
        get
        {
            return this.valorAcrescimoField;
        }
        set
        {
            this.valorAcrescimoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorCancelamento
    {
        get
        {
            return this.valorCancelamentoField;
        }
        set
        {
            this.valorCancelamentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
    public string ValorTotalLiquido
    {
        get
        {
            return this.valorTotalLiquidoField;
        }
        set
        {
            this.valorTotalLiquidoField = value;
        }
    }
}
